name: azkar_counter
description: An elegant and spiritual Azkar counter app by nasihun.com.
publish_to: 'none' 
version: 1.3.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  path_provider: ^2.0.11
  audioplayers: ^5.2.0
  flutter_spinkit: ^5.1.0
  intl: ^0.18.0
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  vibration: ^3.1.3
  file_picker: ^10.2.0
  permission_handler: ^12.0.0+1
  in_app_update: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/UthmanicHafs1 Ver09.otf
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png" # Must include padding
  adaptive_icon_background: "#ffffff" # Or your brand color
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  background_image: "assets/images/gradient_background.png"
  # The main icon for the splash screen
  image: "assets/images/app_icon.png"
  android_gravity: "center"
  ios_content_mode: "scaleAspectFill"
  # Specific configuration for modern Android versions
  android_12:
    image: "assets/images/app_icon.png"
    color: "#4389A2" # Fallback color for the icon background
